### ISSUE TITLE
Code for Life global tour tracker - webpage

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#418]
We would like to create a 'tracker' page for the website. 
This should have a map of where our dev centres are, so that we can create a virtual journey across the world for the Code for Life tour events that are happening in our different dev centres.

It would be great to have photos of the events added once the different events are completed, therefore the webpage needs to be able to show:

- [x] Location of event and school name
- [x] Photos from event
- [ ] Social media post links

Please follow brand colours and fonts:
Fonts: Inter/Space Grotesk
Raspberry: #EE0857
Blue: #00A3E0
Yellow: #FFC709

- [ ] Design 3 options 

Reviewer: @lauracumming

**Comment by evemartin** [comment]
Here is a short screen recording of the new webpage: 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMitkQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--599a1f47b5185f761fff9686cd79aae8515780ec/Screencast%20from%2028-06-24%2010-13-22.webm)

**Comment by lauracumming** [comment]
Great. Can we use a green and blue from Rapid Router please? #86ae18, #00a3e0

**Comment by lauracumming** [comment]
Not sure about the stacked images though. Let's leave it as one image per country. 
Here are the locations: https://www.ocadogroup.com/our-business/our-locations/

**Comment by evemartin** [comment]
Thank you for the comments @lauracumming ! Here's what it looks like with the changes: 
![image](https://github.com/ocadotechnology/codeforlife-design/assets/162978916/a16028aa-4149-40e7-b86e-f0105cd145cf)

**Comment by lauracumming** [comment]
We ca hide the page for now and point to it later.

**Comment by lauracumming** [comment]
Let's zoom into Europe and add the Hatfield text and images - see what it looks like: https://docs.google.com/document/d/1uNsASRHiDey5tYHuB9S0CvR3TNiOhfDscad25nJy1i0/edit?usp=sharing

Once we know the next date, we can add a dotted line to show movement.

**Comment by evemartin** [comment]
I have added the new Hatfield content and made some layout adjustments when the screen is resized - ready for review!

**Comment by faucomte97** [comment]
To be deployed to staging

**Comment by faucomte97** [comment]
Should be on prod now

**Comment by faucomte97** [comment]
It is, page is still a WIP but first stage looking good.
