### ISSUE TITLE
Branding for Python hub

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#423]
**Summary**
We would like to create a look and feel for the new Python Hub. 
We want something that attracts kids from around aged 11 years old. So think teens.

**User story**
_As a teenager that is learning Python for the first time
_I would like to feel confident and excited when looking at the learning resources
_so that I am engaged and keen to learn

**What pages will be changed?**
We will be adding images to the Play and Teach pages on the website, the student dashboard, the resources themselves, and use assets in social media too. We will probably also print some stickers.

**Outcome/deliverable**
Initially, please propose 

- [x] three quick concepts, from these we will need:

Followed by:
- [x] Characters/figures that can be used to 'speak' throughout the resources
- [x] Graphic elements to pick out sections in resources
- [x] Cover graphics for slide and hero image
- [x] Colour palette
- [x] Leading font (for logo and any graphical wording) Body font will remain as _Inter_

**Tools**
Illustrator / Figma

**Concerns**
Ensure all is copyright free 

**Deadline**
As marked by sprints

**Links**
[https://code-for-life.gitbook.io/python-lessons-with-raspberry-pi-ide/3GnBiHhkcxRgUkKhYFz4]

**Reviewer**
@lauracumming 

**People to contact**
@lauracumming 

## Acceptance Criteria
SVGs are saved to folders, artwork is saved to folders, any links and fonts are packaged.

**Comment by ligiaolmos** [comment]
Hi @lauracumming , thanks for the brief, I will start asap and reach out if I have any questions. I assume we don't have a logo yet and the copy in the logo should be "Python Hub" Could you confirm that? Thanks!

**Comment by lauracumming** [comment]
We don't have a logo or a name. There may be something Python based that is sexier than Python hub.  See if you can find anything, otherwsie we can go with 'The Python Hub' or something.

**Comment by ligiaolmos** [comment]
Hi @lauracumming 
I'm attaching the exploration and drafts I'm working on for the Python Hub. As you can see in the files attached there are some suggestions for logo, naming, colours combo and a draft for the portal (I know that is probably not doable to recreate my design suggestion but I had fun exploring how we could apply the branding in a landing page :) For some inspiration for future development). Also, I made some graphics to use in the portal and material and found a 3D icon pack (free to use and edited the colours to match the branding colours selected).

I made a design for the banner header (for now the photos I created using ai models but we can change them if you like). Also in the portal landing exploration you can see a monster I drafted but I have some more sketches that I'm working on.

Let me know what do you think. Perhaps we could schedule a call to review those drafts and discuss your feedback.

Thanks!
Ligia

![01_Portal_draft](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/2776f9ce-da11-4a5a-a412-5a2dfa040579)
![02_Naming](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/ecfd83d5-07fc-4647-88a9-886b7d7185c4)
![03_Colours](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/b6b6a968-7f37-46fe-8b58-72c68c4a71a7)
![04_Logo](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/5a2e28f6-a766-42d8-8601-c4a2db352f2e)
![05_Graphics](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/a2fa9846-1c89-4aac-947c-8f2e51d89dfa)
![06_Hero_header_banner](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/f07c3ed5-d646-4567-889c-191f62e9a729)

**Comment by ligiaolmos** [comment]
Here with Intern as body font and the proposal for branding font 
![Portal](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/1ba40496-328d-4327-820c-a3d09d4a040f)
![Typography](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/b1484dd3-ae5a-4760-b82f-de5d2adde102)

**Comment by lauracumming** [comment]
@ligiaolmos fantastic start to this project! I think Python Lab and Python Den work best.
I think the 2D graphics work well with our overarching brand, but maybe we can bring some 3D into the logo type, like we do with Rapid Router. If we are to use this font, it will need to work with Inter too.

I'll put a call in to talk through it all. 👍

**Comment by ligiaolmos** [comment]
Hi @lauracumming I hope you are well. Here is a concept for the logo which is more typographic and with a 3D feel to it. I'm working on applying it with the header and characters (with some changes in the colors of clothing to match in style). I made a version with a rounded eye and another with a more "fearless" expression on the eyes. What do you think?
<img width="981" alt="Screenshot 2024-06-06 at 18 41 04" src="https://github.com/ocadotechnology/codeforlife-design/assets/163847431/1eedff36-5801-4145-8d41-ca80320c906b">
<img width="1073" alt="Screenshot 2024-06-06 at 18 41 16" src="https://github.com/ocadotechnology/codeforlife-design/assets/163847431/0bca0aaf-b284-4bca-9007-c830a3237ec1">

**Comment by lauracumming** [comment]
Quite like the idea of 'fearless' coming into it all. 👍 We may be able to use that as a hook to get the girls and boys fired up about the learning. 

Also, the fearless eye is suited to an older audience, so let's go with it. Using the navy as the dominant colour for background also works i think. Gives it a more mature feel. and the pink 'pops'

I wonder if any scales can be hinted at too, in the text?

**Comment by ligiaolmos** [comment]
Hi @lauracumming this week I had to work on 6 different prototypes and couldn’t advance much here but next week I will send the logo/branding finalised. Just wanted to clarify what do you mean by "scales can be hinted at too, in the text"? thanks!

**Comment by lauracumming** [comment]
<img width="293" alt="Screenshot 2024-06-14 at 08 36 42" src="https://github.com/ocadotechnology/codeforlife-design/assets/56551296/9d5abc79-3b03-4b8c-9390-9ee48d97bdf8">
texture

**Comment by lauracumming** [comment]
Thinking  a bit of texture would be great?

**Comment by ligiaolmos** [comment]
![Screenshot 2024-06-17 at 16 46 49](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/e1664dfe-e298-4ad3-a141-05c8cfd411c3)

**Comment by ligiaolmos** [comment]
Hi Laura, I've been trying with adding a snake texture, we need to make sure not to compromise legibility and even in a small scale still have good readability so I tested the following options

**Comment by ligiaolmos** [comment]
<img width="776" alt="Screenshot 2024-06-17 at 17 34 49" src="https://github.com/ocadotechnology/codeforlife-design/assets/163847431/6bf4fb25-1ae9-4657-89ff-3262dd1ebbd9">

**Comment by ligiaolmos** [comment]
<img width="548" alt="Screenshot 2024-06-17 at 17 33 28" src="https://github.com/ocadotechnology/codeforlife-design/assets/163847431/1dd6fcfe-3315-4d77-b40a-dd20ec9336dd">

**Comment by ligiaolmos** [comment]
![Screenshot 2024-06-17 at 17 43 38](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/f4fa8387-8f29-48ee-8f7f-60a175cc626e)

**Comment by ligiaolmos** [comment]
<img width="572" alt="Screenshot 2024-06-17 at 17 48 00" src="https://github.com/ocadotechnology/codeforlife-design/assets/163847431/288177a5-fb03-448f-a5c9-798424e0fb5a">

**Comment by ligiaolmos** [comment]
I suggest we go with one of the last 2 as the first one (even if the texture is more realistic) makes the colour less fresh and adds too much detail and we will need to define a minimum size quite big to not loose details.. What do you think?

**Comment by ligiaolmos** [comment]
![banner_portal](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/358ca9c5-ec40-4565-9225-ae5eca480c2e)

**Comment by ligiaolmos** [comment]
![Portal_v2](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/41a8255e-3f72-4281-bacd-6c1a9d5ecd2f)
Here an idea of how we could add the snake texture in other elements like the banner header. Also I recoloured the Kurano characters so we can use as the guide characters for tutorial and materials instead of the monsters.
Let me know what do you think.
Thanks

**Comment by lauracumming** [comment]
These look great @ligiaolmos. I think that first logo works well with the subtle gradient pattern, and then how you bring it into the background ties it all together. Let's lose the pencil, i don't think you need those study elements anymore. The patterns and colours work well.

We can use the characters and maybe dig out some of the artefacts to add interest around concepts etc late along the line.

I think we are there with the look and feel so we can wrap this up with a style guide and save elements into folders.

Then we can look at separate tasks for slides, lessons and webpage etc.

Nice one!

**Comment by ligiaolmos** [comment]
Great! Glad to hear :) I will work on those tweaks and prep the elements to save on the folder in Gdrive. thanks

**Comment by lauracumming** [comment]
Completed
